armorstand:
  menu:
    0_7:
      property: armorstand/size
      name: <blue>Toggle size
      item: bone_meal
      description:
        - <gray>Currently <current>.
        - <gray>Changes the size of
        - <gray>the armor stand.
