name: EasyArmorStands
version: '${version}'
main: me.m56738.easyarmorstands.EasyArmorStands
api-version: 1.19
dependencies:
  - name: HeadDatabase
    required: false
  - name: PlotSquared
    required: false
  - name: Train_Carts
    required: false
  - name: WorldGuard
    required: false
load-after:
  - name: HeadDatabase
  - name: PlotSquared
  - name: Train_Carts
  - name: WorldGuard
