name: EasyArmorStands
version: '${version}'
main: me.m56738.easyarmorstands.EasyArmorStands
author: '56738'
api-version: 1.13
softdepend:
  - HeadDatabase
  - PlotSquared
  - Train_Carts
  - WorldGuard
