[versions]
adventure = "4.23.0"
adventure-platform-mod = "6.5.0-SNAPSHOT"
apiguardian = "1.1.2"
bentobox = "2.7.0-SNAPSHOT"
bstats = "3.1.0"
checker-qual = "3.49.2"
cloud = "2.0.0"
cloud-minecraft = "2.0.0-beta.11"
cloud-minecraft-modded = "2.0.0-beta.12"
commodore = "2.2"
configurate = "4.2.0"
fabric-api = "0.129.0+1.21.8"
fabric-loader = "0.16.14"
fabric-loom = "1.11-SNAPSHOT"
fancyholograms = "2.4.2"
gizmo = "1.0.0"
griefdefender = "2.1.1-SNAPSHOT"
griefprevention = "17.0.0"
hangar-publish-plugin = "0.1.3"
headdatabase-api = "1.3.2"
huskclaims = "1.5.2"
jspecify = "1.0.0"
lands = "7.13.1"
minecraft = "1.21.8"
moddev = "2.0.103"
neoforge = "21.8.2-beta"
neoform = "1.21.8-20250717.133445"
paper = "1.21.7-R0.1-SNAPSHOT"
parchment-mappings = "2025.07.18"
parchment-minecraft = "1.21.8"
plotsquared = "7.5.2"
residence = "4.5._13.1"
run-task = "2.3.1"
shadow = "8.3.6"
towny = "0.101.1.7"
traincarts = "1.21.1-v1"
worldguard = "7.0.14"

[libraries]
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-platform-fabric = { module = "net.kyori:adventure-platform-fabric", version.ref = "adventure-platform-mod" }
adventure-platform-mod-shared = { module = "net.kyori:adventure-platform-mod-shared", version.ref = "adventure-platform-mod" }
adventure-platform-neoforge = { module = "net.kyori:adventure-platform-neoforge", version.ref = "adventure-platform-mod" }
apiguardian-api = { module = "org.apiguardian:apiguardian-api", version.ref = "apiguardian" }
bentobox = { module = "world.bentobox:bentobox", version.ref = "bentobox" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
checker-qual = { module = "org.checkerframework:checker-qual", version.ref = "checker-qual" }
cloud-annotations = { module = "org.incendo:cloud-annotations", version.ref = "cloud" }
cloud-core = { module = "org.incendo:cloud-core", version.ref = "cloud" }
cloud-fabric = { module = "org.incendo:cloud-fabric", version.ref = "cloud-minecraft-modded" }
cloud-minecraft-extras = { module = "org.incendo:cloud-minecraft-extras", version.ref = "cloud-minecraft" }
cloud-minecraft-modded-common = { module = "org.incendo:cloud-minecraft-modded-common", version.ref = "cloud-minecraft-modded" }
cloud-neoforge = { module = "org.incendo:cloud-neoforge", version.ref = "cloud-minecraft-modded" }
cloud-paper = { module = "org.incendo:cloud-paper", version.ref = "cloud-minecraft" }
commodore = { module = "me.lucko:commodore", version.ref = "commodore" }
configurate-core = { module = "org.spongepowered:configurate-core", version.ref = "configurate" }
configurate-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fancyholograms = { module = "de.oliver:FancyHolograms", version.ref = "fancyholograms" }
gizmo-common = { module = "me.m56738.gizmo:gizmo-common", version.ref = "gizmo" }
gizmo-bukkit = { module = "me.m56738.gizmo:gizmo-bukkit", version.ref = "gizmo" }
griefdefender-api = { module = "com.griefdefender:api", version.ref = "griefdefender" }
griefprevention = { module = "com.github.GriefPrevention:GriefPrevention", version.ref = "griefprevention" }
headdatabase-api = { module = "com.arcaniax:HeadDatabase-API", version.ref = "headdatabase-api" }
huskclaims-bukkit = { module = "net.william278.huskclaims:huskclaims-bukkit", version.ref = "huskclaims" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
lands-api = { module = "com.github.angeschossen:LandsAPI", version.ref = "lands" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
plotsquared-bukkit = { module = "com.intellectualsites.plotsquared:plotsquared-bukkit", version.ref = "plotsquared" }
plotsquared-core = { module = "com.intellectualsites.plotsquared:plotsquared-core", version.ref = "plotsquared" }
residence = { module = "com.bekvon.bukkit.residence:Residence", version.ref = "residence" }
towny = { module = "com.palmergames.bukkit.towny:towny", version.ref = "towny" }
traincarts = { module = "com.bergerkiller.bukkit:TrainCarts", version.ref = "traincarts" }
worldguard = { module = "com.sk89q.worldguard:worldguard-bukkit", version.ref = "worldguard" }

[plugins]
fabric-loom =  { id = "fabric-loom", version.ref = "fabric-loom" }
hangar-publish = { id = "io.papermc.hangar-publish-plugin", version.ref = "hangar-publish-plugin" }
moddev = { id = "net.neoforged.moddev", version.ref = "moddev" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-task" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
