[versions]
adventure-api = "4.16.0"
adventure-platform = "4.3.3-SNAPSHOT"
brigadier = "1.0.17"
bstats = "3.0.2"
bukkit = "1.8.8-R0.1-SNAPSHOT"
cloud = "2.0.0-rc.1"
cloud-minecraft = "2.0.0-SNAPSHOT"
commodore = "2.2"
configurate = "4.1.2"
hangar-publish-plugin = "0.1.2"
headdatabase-api = "1.3.1"
joml = "1.10.5"
shadow = "8.1.1"
traincarts = "1.19.4-v2"
worldguard-v6 = "6.2"
worldguard-v7 = "7.0.9"

[libraries]
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure-api" }
adventure-platform-bukkit = { module = "net.kyori:adventure-platform-bukkit", version.ref = "adventure-platform" }
adventure-text-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure-api" }
adventure-text-serializer-gson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "adventure-api" }
adventure-text-serializer-legacy = { module = "net.kyori:adventure-text-serializer-legacy", version.ref = "adventure-api" }
adventure-text-serializer-plain = { module = "net.kyori:adventure-text-serializer-plain", version.ref = "adventure-api" }
brigadier = { module = "com.mojang:brigadier", version.ref = "brigadier" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
bukkit = { module = "org.bukkit:bukkit", version.ref = "bukkit" }
cloud-annotations = { module = "org.incendo:cloud-annotations", version.ref = "cloud" }
cloud-minecraft-extras = { module = "org.incendo:cloud-minecraft-extras", version.ref = "cloud-minecraft" }
cloud-paper = { module = "org.incendo:cloud-paper", version.ref = "cloud-minecraft" }
commodore = { module = "me.lucko:commodore", version.ref = "commodore" }
configurate-core = { module = "org.spongepowered:configurate-core", version.ref = "configurate" }
configurate-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }
headdatabase-api = { module = "com.arcaniax:HeadDatabase-API", version.ref = "headdatabase-api" }
joml = { module = "org.joml:joml", version.ref = "joml" }
traincarts = { module = "com.bergerkiller.bukkit:TrainCarts", version.ref = "traincarts" }
worldguard-v6 = { module = "com.sk89q.worldguard:worldguard-legacy", version.ref = "worldguard-v6" }
worldguard-v7 = { module = "com.sk89q.worldguard:worldguard-bukkit", version.ref = "worldguard-v7" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
hangar-publish = { id = "io.papermc.hangar-publish-plugin", version.ref = "hangar-publish-plugin" }
