[versions]
adventure-api = "4.17.0"
adventure-platform = "4.3.4"
brigadier = "1.0.17"
bstats = "3.0.2"
bukkit = "1.8.8-R0.1-SNAPSHOT"
cloud = "2.0.0"
cloud-minecraft = "2.0.0-beta.10"
commodore = "2.2"
configurate = "4.1.2"
griefdefender = "2.1.0-SNAPSHOT"
hangar-publish-plugin = "0.1.2"
headdatabase-api = "1.3.2"
joml = "1.10.8"
lands = "7.10.6"
residence = "4.5._13.1"
run-task = "2.3.1"
shadow = "8.3.2"
traincarts = "1.19.4-v2"
worldguard-v6 = "6.2"
worldguard-v7 = "7.0.9"

[libraries]
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure-api" }
adventure-platform-bukkit = { module = "net.kyori:adventure-platform-bukkit", version.ref = "adventure-platform" }
adventure-text-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure-api" }
adventure-text-serializer-gson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "adventure-api" }
adventure-text-serializer-legacy = { module = "net.kyori:adventure-text-serializer-legacy", version.ref = "adventure-api" }
adventure-text-serializer-plain = { module = "net.kyori:adventure-text-serializer-plain", version.ref = "adventure-api" }
brigadier = { module = "com.mojang:brigadier", version.ref = "brigadier" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
bukkit = { module = "org.bukkit:bukkit", version.ref = "bukkit" }
cloud-annotations = { module = "org.incendo:cloud-annotations", version.ref = "cloud" }
cloud-minecraft-extras = { module = "org.incendo:cloud-minecraft-extras", version.ref = "cloud-minecraft" }
cloud-paper = { module = "org.incendo:cloud-paper", version.ref = "cloud-minecraft" }
commodore = { module = "me.lucko:commodore", version.ref = "commodore" }
configurate-core = { module = "org.spongepowered:configurate-core", version.ref = "configurate" }
configurate-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }
griefdefender-api = { module = "com.griefdefender:api", version.ref = "griefdefender" }
headdatabase-api = { module = "com.arcaniax:HeadDatabase-API", version.ref = "headdatabase-api" }
joml = { module = "org.joml:joml", version.ref = "joml" }
lands-api = { module = "com.github.angeschossen:LandsAPI", version.ref = "lands" }
residence = { module = "com.bekvon.bukkit.residence:Residence", version.ref = "residence" }
traincarts = { module = "com.bergerkiller.bukkit:TrainCarts", version.ref = "traincarts" }
worldguard-v6 = { module = "com.sk89q.worldguard:worldguard-legacy", version.ref = "worldguard-v6" }
worldguard-v7 = { module = "com.sk89q.worldguard:worldguard-bukkit", version.ref = "worldguard-v7" }

[plugins]
hangar-publish = { id = "io.papermc.hangar-publish-plugin", version.ref = "hangar-publish-plugin" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-task" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
