[versions]
apiguardian = "1.1.2"
bentobox = "2.7.0-SNAPSHOT"
bstats = "3.1.0"
checker-qual = "3.49.2"
cloud = "2.0.0"
cloud-minecraft = "2.0.0-beta.10"
commodore = "2.2"
configurate = "4.2.0"
fancyholograms = "2.4.2"
gizmo = "1.0.0"
griefdefender = "2.1.1-SNAPSHOT"
griefprevention = "17.0.0"
hangar-publish-plugin = "0.1.3"
headdatabase-api = "1.3.2"
huskclaims = "1.5.2"
lands = "7.13.1"
paper = "1.21.7-R0.1-SNAPSHOT"
plotsquared = "7.5.2"
residence = "4.5._13.1"
run-task = "2.3.1"
shadow = "8.3.6"
towny = "0.101.1.7"
traincarts = "1.21.1-v1"
worldguard = "7.0.14"

[libraries]
apiguardian-api = { module = "org.apiguardian:apiguardian-api", version.ref = "apiguardian" }
bentobox = { module = "world.bentobox:bentobox", version.ref = "bentobox" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
checker-qual = { module = "org.checkerframework:checker-qual", version.ref = "checker-qual" }
cloud-annotations = { module = "org.incendo:cloud-annotations", version.ref = "cloud" }
cloud-minecraft-extras = { module = "org.incendo:cloud-minecraft-extras", version.ref = "cloud-minecraft" }
cloud-paper = { module = "org.incendo:cloud-paper", version.ref = "cloud-minecraft" }
commodore = { module = "me.lucko:commodore", version.ref = "commodore" }
configurate-core = { module = "org.spongepowered:configurate-core", version.ref = "configurate" }
configurate-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }
fancyholograms = { module = "de.oliver:FancyHolograms", version.ref = "fancyholograms" }
gizmo-bukkit = { module = "me.m56738.gizmo:gizmo-bukkit", version.ref = "gizmo" }
griefdefender-api = { module = "com.griefdefender:api", version.ref = "griefdefender" }
griefprevention = { module = "com.github.GriefPrevention:GriefPrevention", version.ref = "griefprevention" }
headdatabase-api = { module = "com.arcaniax:HeadDatabase-API", version.ref = "headdatabase-api" }
huskclaims-bukkit = { module = "net.william278.huskclaims:huskclaims-bukkit", version.ref = "huskclaims" }
lands-api = { module = "com.github.angeschossen:LandsAPI", version.ref = "lands" }
plotsquared-bukkit = { module = "com.intellectualsites.plotsquared:plotsquared-bukkit", version.ref = "plotsquared" }
plotsquared-core = { module = "com.intellectualsites.plotsquared:plotsquared-core", version.ref = "plotsquared" }
residence = { module = "com.bekvon.bukkit.residence:Residence", version.ref = "residence" }
towny = { module = "com.palmergames.bukkit.towny:towny", version.ref = "towny" }
traincarts = { module = "com.bergerkiller.bukkit:TrainCarts", version.ref = "traincarts" }
worldguard = { module = "com.sk89q.worldguard:worldguard-bukkit", version.ref = "worldguard" }

[plugins]
hangar-publish = { id = "io.papermc.hangar-publish-plugin", version.ref = "hangar-publish-plugin" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-task" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
