slots:
  easyarmorstands:copy:
    column: 4
    config:
      button:
        description:
        - <lang:easyarmorstands.menu.copy.description>
        name: <lang:easyarmorstands.menu.copy>
      item:
        name: <gold><lang:easyarmorstands.copy.item.name:'<element>'>
    row: 1
    type: easyarmorstands:copy
  easyarmorstands:destroy:
    column: 8
    config:
      item:
        description:
        - <lang:easyarmorstands.menu.destroy.description>
        name: <lang:easyarmorstands.menu.destroy>
        type: tnt
    row: 0
    type: easyarmorstands:destroy
  easyarmorstands:entity/custom_name:
    column: 4
    config:
      property: easyarmorstands:entity/custom_name
    row: 0
    type: easyarmorstands:property
  easyarmorstands:entity/glowing:
    column: 5
    config:
      property: easyarmorstands:entity/glowing
    row: 0
    type: easyarmorstands:property
  easyarmorstands:entity/silent:
    column: 7
    config:
      property: easyarmorstands:entity/silent
    row: 0
    type: easyarmorstands:property
  easyarmorstands:entity/visible:
    column: 6
    config:
      property: easyarmorstands:entity/visible
    row: 0
    type: easyarmorstands:property
title: <type>
version:
  game: 1.8.8
