update-check: true

server-side-translation: true

tool:
  type: blaze_rod
  name: <gold><lang:easyarmorstands.tool-name>
  description:
    - <gray><lang:easyarmorstands.hint.select-entity>
    - <gray><lang:easyarmorstands.hint.spawn-entity>
    - <gray><lang:easyarmorstands.hint.deselect-entity>

message-formats:
  TITLE: '<gold><message>:'
  SUCCESS: <green><message>
  WARNING: <yellow><message>
  ERROR: <red><message>
  HINT: <gray><message>
  CHAT_BUTTON: <gray>[<message>]
  HOVER: <gray><message>
  BUTTON_NAME: <blue><message>
  BUTTON_DESCRIPTION: <gray><message>

menu-background:
  type: easyarmorstands:background
  config:
    item:
      type: light_blue_stained_glass_pane
      name: ''

editor-scale-min-distance: 5
editor-scale-max-distance: 64
editor-range: 64
editor-selection-range: 10
editor-look-threshold: 0.1

interpolation-ticks: 1

swap-hands-button: '[<key:key.swapOffhand>]'
