on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: 'true'
      - uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          java-version: '25'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
      - name: Build
        run: ./gradlew build
      - name: Publish to repository
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/v4') }}
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_m56738Username: ${{ secrets.MAVEN_M56738_USERNAME }}
          ORG_GRADLE_PROJECT_m56738Password: ${{ secrets.MAVEN_M56738_PASSWORD }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Package
          path: |
            paper/build/EasyArmorStands-Paper-*.jar
      - name: Update description
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: ./gradlew modrinthSyncBody syncAllPagesToHangar
        env:
          HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      - name: Create release
        if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          body_path: CHANGELOG.md
          files: |
            paper/build/EasyArmorStands-Paper-*.jar
      - name: Publish release
        if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
        run: ./gradlew modrinth publishAllPublicationsToHangar
        env:
          HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
