on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: 'true'
      - uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
      - name: Build
        run: ./gradlew build
      - name: Publish to repository
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_MGDevUsername: ${{ secrets.MAVEN_USERNAME }}
          ORG_GRADLE_PROJECT_MGDevPassword: ${{ secrets.MAVEN_PASSWORD }}
          ORG_GRADLE_PROJECT_m56738Username: ${{ secrets.MAVEN_M56738_USERNAME }}
          ORG_GRADLE_PROJECT_m56738Password: ${{ secrets.MAVEN_M56738_PASSWORD }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Package
          path: build/EasyArmorStands-*.jar
          archive: 'false'
      - name: Update description
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: ./gradlew modrinthSyncBody syncAllPagesToHangar
        env:
          HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      - name: Create release
        if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        with:
          body_path: CHANGELOG.md
          files: build/EasyArmorStands-*.jar
      - name: Publish release
        if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
        run: ./gradlew modrinth publishAllPublicationsToHangar
        env:
          HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
