on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: 'true'
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
      - name: Build
        run: ./gradlew build
      - name: Publish to repository
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_MGDevUsername: ${{ secrets.MAVEN_USERNAME }}
          ORG_GRADLE_PROJECT_MGDevPassword: ${{ secrets.MAVEN_PASSWORD }}
          ORG_GRADLE_PROJECT_m56738Username: ${{ secrets.MAVEN_M56738_USERNAME }}
          ORG_GRADLE_PROJECT_m56738Password: ${{ secrets.MAVEN_M56738_PASSWORD }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Package
          path: easyarmorstands-plugin/build/EasyArmorStands-*.jar
          archive: 'false'
      - name: Update description
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: ./gradlew modrinthSyncBody syncAllPagesToHangar
        env:
          HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      - name: Create release
        if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          body_path: CHANGELOG.md
          files: easyarmorstands-plugin/build/EasyArmorStands-*.jar
      - name: Publish release
        if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
        run: ./gradlew modrinth publishAllPublicationsToHangar
        env:
          HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
